### ISSUE TITLE
ToDo List packaging

### ISSUE THREAD

**Issue by VincentAuriau** [artefactory/choice-learn#50]
- [x] better handling of dependencies
- [x] PyPI formatting
- [x] poetry
- [x] item/item-full signature to be kepts ?
- [x] Possibility to load SwissMetro on Long format for example
- [x] conditional Logit example main on SwissMetro
- [x] ADD: Regularization ?
- [x] ENH: naming of weights in .report
